## 2.3 パーセプトロンの実装

### 2.3.1 簡単な実装

In [16]:
def AND(x1, x2) -> int:
    w1:float = 0.5   
    w2:float = 0.5    
    theta:float = 0.7    
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1

In [17]:
print(AND(0, 0))
print(AND(1, 0))
print(AND(0, 1))
print(AND(1, 1))

0
0
0
1


### 2.3.2 重みとバイアスの導入

In [18]:
import numpy as np
from numpy import ndarray

In [19]:
x:ndarray = np.array([0, 1])
x

array([0, 1])

In [20]:
w:ndarray = np.array([0.5, 0.5])
w

array([0.5, 0.5])

In [21]:
バイアス:float = -0.7

In [22]:
w*x

array([0. , 0.5])

In [23]:
np.sum(w*x)

0.5

In [24]:
print("### およそ-0.2")
np.sum(w*x) + バイアス

### およそ-0.2


-0.19999999999999996

### 2.3.3 重みとバイアスによる実装

In [25]:
def AND(x1:int, x2:int) -> int:
    x:ndarray = np.array([x1, x2])
    w:ndarray = np.array([0.5, 0.5])
    バイアス = -0.7
    tmp = np.sum(w*x) + バイアス
    if tmp <= 0:
        return 0
    else:
        return 1        

In [26]:
print(AND(0, 0))
print(AND(1, 0))
print(AND(0, 1))
print(AND(1, 1))

0
0
0
1


In [45]:
def NAND(x1:int, x2:int) -> int:
    x:ndarray = np.array([x1, x2])
    w:ndarray = np.array([-0.5, -0.5]) # 重みとバイアスだけがANDと違う
    b = 0.7
    tmp = np.sum(w*x) + b
    if tmp <= 0:
        return 0
    else:
        return 1   

In [46]:
print(NAND(0, 0))
print(NAND(1, 0))
print(NAND(0, 1))
print(NAND(1, 1))

1
1
1
0


In [47]:
def OR(x1:int, x2:int) -> int:
    x1:ndarray = np.array([x1, x2])
    w:ndarray = np.array([0.5, 0.5]) # 重みとバイアスだけがANDと違う
    b = -0.2
    tmp = np.sum(w*x1) + b
    if tmp <= 0:
        return 0
    else:
        return 1   

In [48]:
print(OR(0, 0))
print(OR(1, 0))
print(OR(0, 1))
print(OR(1, 1))

0
1
1
1


### XORゲートの実装

In [51]:
def XOR(x1:int, x2:int) -> int:
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y