## 2.3 パーセプトロンの実装

### 2.3.1 簡単な実装

In [1]:
def AND(入力1, 入力2) -> int:
    重み1:float = 0.5   
    重み2:float = 0.5    
    シータ:float = 0.7    
    tmp = 入力1*重み1 + 入力2*重み2
    if tmp <= シータ:
        return 0
    elif tmp > シータ:
        return 1

In [2]:
print(AND(0, 0))
print(AND(1, 0))
print(AND(0, 1))
print(AND(1, 1))

0
0
0
1


### 2.3.2 重みとバイアスの導入

In [3]:
import numpy as np
from numpy import ndarray

In [4]:
入力:ndarray = np.array([0, 1])
入力

array([0, 1])

In [5]:
重み:ndarray = np.array([0.5, 0.5])
重み

array([0.5, 0.5])

In [6]:
バイアス:float = -0.7

In [7]:
重み*入力

array([0. , 0.5])

In [8]:
np.sum(重み*入力)

0.5

In [9]:
print("### およそ-0.2")
np.sum(重み*入力) + バイアス

### およそ-0.2


-0.19999999999999996

### 2.3.3 重みとバイアスによる実装

In [10]:
def AND(入力1:int, 入力2:int) -> int:
    入力:ndarray = np.array([入力1, 入力2])
    重み:ndarray = np.array([0.5, 0.5])
    バイアス = -0.7
    tmp = np.sum(重み*入力) + バイアス
    if tmp <= 0:
        return 0
    else:
        return 1        

In [11]:
print(AND(0, 0))
print(AND(1, 0))
print(AND(0, 1))
print(AND(1, 1))

0
0
0
1


In [12]:
def NAND(入力1:int, 入力2:int) -> int:
    入力:ndarray = np.array([入力1, 入力2])
    重み:ndarray = np.array([-0.5, -0.5]) # 重みとバイアスだけがANDと違う
    バイアス = 0.7
    tmp = np.sum(重み*入力) + バイアス
    if tmp <= 0:
        return 0
    else:
        return 1   

In [13]:
print(NAND(0, 0))
print(NAND(1, 0))
print(NAND(0, 1))
print(NAND(1, 1))

1
1
1
0


In [14]:
def OR(入力1:int, 入力2:int) -> int:
    入力:ndarray = np.array([入力1, 入力2])
    重み:ndarray = np.array([0.5, 0.5]) # 重みとバイアスだけがANDと違う
    バイアス = -0.2
    tmp = np.sum(重み*入力) + バイアス
    if tmp <= 0:
        return 0
    else:
        return 1   

In [15]:
print(OR(0, 0))
print(OR(1, 0))
print(OR(0, 1))
print(OR(1, 1))

0
1
1
1
