In [2]:
import numpy as np

### ソフトマックス関数

In [3]:
a = np.array([0.3, 2.9, 4.0])

In [4]:
a

array([0.3, 2.9, 4. ])

In [5]:
exp_a = np.exp(a) # 指数関数

In [6]:
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [9]:
sum_exp_a = np.sum(exp_a)

In [10]:
sum_exp_a

74.1221542101633

In [11]:
y = exp_a / sum_exp_a

In [12]:
y

array([0.01821127, 0.24519181, 0.73659691])

### ソフトマックス関数の実装上の注意

In [13]:
a = np.array([1010, 1000, 990])

In [14]:
a

array([1010, 1000,  990])

In [17]:
np.exp(a) / np.sum(np.exp(a)) # ソフトマックス関数の計算。正しく計算されない

C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.
C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, nan, nan])

In [18]:
c = np.max(a)

In [19]:
c

1010

In [20]:
a - c

array([  0, -10, -20])

In [21]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

#### ソフトマックス関数

In [25]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) # オーバーフロー対策
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

### 3.5.3 ソフトマックス関数の特徴

In [26]:
a = np.array([0.3, 2.9, 4.0])

In [27]:
a

array([0.3, 2.9, 4. ])

In [28]:
y = softmax(a)

In [29]:
y

array([0.01821127, 0.24519181, 0.73659691])

In [32]:
np.sum(y) # ソフトマックス関数の出力の総和は「1」になる

1.0