### 3.6.1 MNIST データセット

In [50]:
import sys, os
import pickle

In [51]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [52]:
sys.path.append(os.pardir)

In [53]:
from dataset.mnist import load_mnist

In [54]:
# (訓練画像, 訓練ラベル),(テスト画像, テストラベル)
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

In [55]:
x_train.shape

(60000, 784)

In [56]:
t_train.shape

(60000,)

In [57]:
x_test.shape

(10000, 784)

In [58]:
t_test.shape

(10000,)

In [59]:
import numpy as np
from PIL import Image

In [60]:
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

In [61]:
# (訓練画像, 訓練ラベル),(テスト画像, テストラベル)
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

In [62]:
img = x_train[0]

In [63]:
label = t_train[0]
label

5

In [64]:
print(img.shape)

(784,)


In [65]:
img = img.reshape(28, 28)

In [66]:
# 画像の表示
# img_show(img)

### 3.6.2 ニューラルネットワークの推論処理

In [67]:
def get_data():
    (x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)
    return x_test, t_test

In [68]:
def init_network():
    """学習済みの重みパラメータをsample_weight.plkに読み込ませる
    """
    with open(r".\ch03\sample_weight.pkl", "rb") as f:
        network = pickle.load(f)
    return network

In [69]:
def predict(network, x):
    W1, W2, W3 = network["W1"], network["W2"], network["W3"]
    b1, b2, b3 = network["b1"], network["b2"], network["b3"]
    
    a1 = x @ W1 + b1
    z1 = sigmoid(a1)
    
    a2 = z1 @ W2+ b2
    z2 = sigmoid(a2)
    
    a3 = z2 @ W3+ b3
    y= sigmoid(a3)
    
    return y
    

In [70]:
# MNISTのデータセット取得
x, t = get_data()

In [71]:
print(x)
print(len(x))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
10000


In [72]:
print(t)
print(len(t))

[7 2 1 ... 4 5 6]
10000


In [73]:
# 教育済みニューラルネットワークのデータ読み込み
network = init_network()

In [74]:
accuracy_cnt = 0

In [75]:
print(len(x))
for i in range(len(x)):
    y = predict(network, x[i])
    # np.argmax(y)
    # 配列yの中で最大の値を持つ要素のインデックスを取得
    p = np.argmax(y) 
    if p == t[i]:
        accuracy_cnt += 1
    

10000


<ipython-input-51-b683d5dd8fa4>:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


In [76]:
print("Accuracy(認識精度):" + str(float(accuracy_cnt) / len(x)))

Accuracy(認識精度):0.9207


### 3.6.3 バッチ処理

In [77]:
x, _ = get_data()

In [78]:
network = init_network()

In [79]:
W1, W2, W3 = network["W1"], network["W2"], network["W3"]

In [80]:
x.shape

(10000, 784)

In [81]:
W1.shape

(784, 50)

In [82]:
W2.shape

(50, 100)

In [83]:
W3.shape

(100, 10)

In [84]:
x, t = get_data()

In [85]:
network = init_network()

In [86]:
batch_size = 100 # バッチの数

In [87]:
accuracy_cnt = 0

In [88]:
for i in range(0, len(x), batch_size): # range(0, 10000, 100)
    x_batch = x[i:i+batch_size]
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis=1)
    accuracy_cnt += np.sum(p == t[i:i+batch_size])
print(accuracy_cnt)

9207


<ipython-input-51-b683d5dd8fa4>:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))


In [89]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [96]:
# 0から9の間を3ステップずつ
list(range(0, 10, 3))

[0, 3, 6, 9]

In [91]:
# np.argmax(x, args=1)の例
x = np.array([[0.2, 0.5, 0.3],  [0.3, 0.1, 0.6], [0.2, 0.5, 0.3], [0.8, 0.1, 0.1]])
print(x)

[[0.2 0.5 0.3]
 [0.3 0.1 0.6]
 [0.2 0.5 0.3]
 [0.8 0.1 0.1]]


In [92]:
y = np.argmax(x, axis=1)

In [94]:
print("0.5, 0.6, 0.5, 0.8のインデックス位置が表示される(それらが最大であるため)")
y 

0.5, 0.6, 0.5, 0.8のインデックス位置が表示される(それらが最大であるため)


array([1, 2, 1, 0], dtype=int64)