### 3.6.1 MNIST データセット

In [78]:
import sys, os
import pickle

In [79]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [80]:
sys.path.append(os.pardir)

In [81]:
from dataset.mnist import load_mnist

In [82]:
# (訓練画像, 訓練ラベル),(テスト画像, テストラベル)
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

In [83]:
x_train.shape

(60000, 784)

In [84]:
t_train.shape

(60000,)

In [85]:
x_test.shape

(10000, 784)

In [86]:
t_test.shape

(10000,)

In [87]:
import numpy as np
from PIL import Image

In [88]:
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

In [89]:
# (訓練画像, 訓練ラベル),(テスト画像, テストラベル)
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

In [90]:
img = x_train[0]

In [91]:
label = t_train[0]
label

5

In [92]:
print(img.shape)

(784,)


In [93]:
img = img.reshape(28, 28)

In [94]:
# 画像の表示
# img_show(img)

### 3.6.2 ニューラルネットワークの推論処理

In [95]:
def get_data():
    (x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)
    return x_test, t_test

In [96]:
def init_network():
    """学習済みの重みパラメータをsample_weight.plkに読み込ませる
    """
    with open(r".\ch03\sample_weight.pkl", "rb") as f:
        network = pickle.load(f)
    return network

In [97]:
def predict(network, x):
    W1, W2, W3 = network["W1"], network["W2"], network["W3"]
    b1, b2, b3 = network["b1"], network["b2"], network["b3"]
    
    a1 = x @ W1 + b1
    z1 = sigmoid(a1)
    
    a2 = z1 @ W2+ b2
    z2 = sigmoid(a2)
    
    a3 = z2 @ W3+ b3
    y= sigmoid(a3)
    
    return y
    

In [98]:
# MNISTのデータセット取得
x, t = get_data()

In [99]:
print(x)
print(len(x))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
10000


In [100]:
print(t)
print(len(t))

[7 2 1 ... 4 5 6]
10000


In [101]:
# 教育済みニューラルネットワークのデータ読み込み
network = init_network()

In [102]:
accuracy_cnt = 0

In [103]:
print(len(x))
for i in range(len(x)):
    y = predict(network, x[i])
    # np.argmax(y)
    # 配列yの中で最大の値を持つ要素のインデックスを取得
    p = np.argmax(y) 
    if p == t[i]:
        accuracy_cnt += 1
    

10000


C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [104]:
print("Accuracy(認識精度):" + str(float(accuracy_cnt) / len(x)))

Accuracy(認識精度):0.9207
